language: php

php:
  - 7.2

sudo: false

services:
  - mysql

before_script:
  - mysql -e 'create database if not exists axe_test;'
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - vendor/bin/phpunit