language: php

php:
  - 7

sudo: false

matrix:
  fast_finish: true

services:
  - mysql

before_script:
  - mysql -e 'create database if not exists axe_test;'
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - composer test