language: php

php:
  - 7.1
  - 7.2

sudo: false

matrix:
  fast_finish: true

services:
  - mysql

before_script:
  - mysql -e 'create database if not exists axe_test;'
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction
script:
  - ./vendor/bin/phpunit